from django.contrib import admin
from dfirtrack_config.models import ArtifactExporterSpreadsheetXlsConfigModel, SystemExporterMarkdownConfigModel, SystemExporterSpreadsheetCsvConfigModel, SystemExporterSpreadsheetXlsConfigModel, SystemImporterFileCsvConfigbasedConfigModel, SystemImporterFileCsvFormbasedConfigModel

# all registered models will show up in admin app
admin.site.register(ArtifactExporterSpreadsheetXlsConfigModel)
admin.site.register(SystemExporterMarkdownConfigModel)
admin.site.register(SystemExporterSpreadsheetCsvConfigModel)
admin.site.register(SystemExporterSpreadsheetXlsConfigModel)
admin.site.register(SystemImporterFileCsvConfigbasedConfigModel)
admin.site.register(SystemImporterFileCsvFormbasedConfigModel)
