# Generated by Django 3.2.12 on 2022-02-18 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dfirtrack_main', '0024_user_assignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dfirtrack_config', '0024_system_list_toggle'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfigmodel',
            name='filter_system_list_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filter_system_list_use', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userconfigmodel',
            name='filter_assignment_view_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filter_assignment_view_tag', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='userconfigmodel',
            name='filter_system_list_tag',
        ),
        migrations.AddField(
            model_name='userconfigmodel',
            name='filter_system_list_tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='filter_system_list_tag', to='dfirtrack_main.Tag'),
        ),
    ]
