# Generated by Django 3.2.12 on 2022-02-23 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('dfirtrack_main', '0024_user_assignment'),
        ('dfirtrack_config', '0025_assigned_users_spreadsheet_export'),
    ]

    operations = [
        migrations.DeleteModel('userconfigmodel'),
        migrations.CreateModel(
            name='userconfigmodel',
            fields=(
                (
                    'content_type',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='contenttypes.contenttype',
                    ),
                ),
                (
                    'filter_list_case',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='filter_list_case',
                        to='dfirtrack_main.case',
                    ),
                ),
                (
                    'filter_list_tag',
                    models.ManyToManyField(
                        blank=True,
                        related_name='filter_list_tag',
                        to='dfirtrack_main.Tag',
                    ),
                ),
                (
                    'filter_list_assigned_to_user_id',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='filter_list_assigned_to_user_id',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'filter_view',
                    models.CharField(max_length=50),
                ),
                (
                    'filter_view_show',
                    models.JSONField(blank=True, null=True),
                ),
                (
                    'object_id',
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    'user_config_id',
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    'user_config_username',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='filter_username',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ),
        ),
        migrations.AlterUniqueTogether(
            name='userconfigmodel',
            unique_together={('user_config_username', 'filter_view')},
        ),
    ]
