# Generated by Django 5.0.2 on 2024-03-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dfirtrack_config", "0026_refactor_user_config"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userconfigmodel",
            name="filter_list_assigned_to_user_id",
        ),
        migrations.RemoveField(
            model_name="userconfigmodel",
            name="filter_list_case",
        ),
        migrations.RemoveField(
            model_name="userconfigmodel",
            name="filter_list_tag",
        ),
        migrations.AddField(
            model_name="userconfigmodel",
            name="filter_query",
            field=models.TextField(blank=True),
        ),
    ]
