# Generated by Django 3.2 on 2021-06-14 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dfirtrack_main', '0017_simplify_system_times'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, unique=True)),
                ('content', models.TextField()),
                ('version', models.IntegerField(editable=False)),
                ('note_create_time', models.DateTimeField(auto_now_add=True)),
                ('note_modify_time', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dfirtrack_main.case')),
                ('note_created_by_user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='note_created_by', to=settings.AUTH_USER_MODEL)),
                ('note_modified_by_user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='note_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
